version: '3.8'

services:
  stock-api:
    image: 'ghcr.io/ozon-edu-csharp-2021/stock-api:main'
    hostname: stock_api
    ports:
      - "8081:80"
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5427;Database=stock-api;Username=postgres;Password=stockApiPassword"
    depends_on:
      - stock-api-db

  emailing-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/emailing-service:main'
    hostname: emailing_service
    ports:
      - "8082:80"

  employees-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/employees-service:main'
    hostname: employees_service
    ports:
      - "8083:80"
    depends_on:
      - employees-service-postgres-db
    volumes:
      - ./src:/src

  supply-service:
    image: 'ghcr.io/ozon-edu-csharp-2021/supply-service:main'
    environment:
      DbConfiguration__ConnectionString: "Host=host.docker.internal;Port=5426;Database=supply-service;Username=postgres;Password=supplyServicePassword"
    hostname: supply_service
    ports:
      - "8084:80"
    depends_on:
      - supply-service-db

  merchendise-service:
    build:
      context: .
      dockerfile: Dockerfile
    hostname: merchendise_service
    ports:
      - "8080:5000"
    environment:
      DatabaseConnectionOptions__ConnectionString: "Host=host.docker.internal;Port=5428;Database=merch-service;Username=postgres;Password=merchServicePassword"
    depends_on:
      - merchendise-service-db

  supply-service-db:
    image: postgres:latest
    ports:
      - "5426:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: supplyServicePassword
      POSTGRES_DB: supply-service

  employees-service-db:
    image: postgres:latest
    ports:
      - "5425:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: employees-service
    volumes:
      - ./db/employees-service-postgres-db/dbdata:/var/lib/postgresql/data"

  stock-api-db:
    image: postgres:latest
    ports:
      - "5427:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: stockApiPassword
      POSTGRES_DB: stock-api

  merchendise-service-db:
    image: postgres:latest
    ports:
      - "5428:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: merchServicePassword
      POSTGRES_DB: merch-service